### ISSUE TITLE
Release ADAM version 1.0.0

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1089]
_Timeline:_ End summer 2017.
_Release goal:_ This will be the first production release of ADAM. This release is intended to just be a small cleanup release on top of 0.21.0. The main goals are to have compete documentation, a stable public interface, and publicized downstream workflows.

Releases
- [x] Release ADAM 0.20.0 #1048 
- [x] Release ADAM 0.21.0 #1088 
- [ ] Release bdg-formats 1.0.0 https://github.com/bigdatagenomics/bdg-formats/issues/93

Algorithmic bugs/cleanup:
- [ ] MdTag.getReference on SKIP operator #742 

Dependency/build cleanup:
- [ ] Kryo version issues #995 
- [ ] Enforce import guidelines #445 
- [ ] Enforce semantic versioning #338 

CI:
- [ ] Have (and run) regression testing suite #120
- [x] Clean cruft up from builds #1038 

New features:
- [ ] Develop method for addressing schema #345 

Documentation:
- [x] Add docs about building downstream apps #291 
- [ ] Annotate classes with production worthiness #123

Downstream workflows:
- [ ] Viz: Have [Mango](https://github.com/bigdatagenomics/mango) operational and post preprint
- [ ] Variant calling: Have [Avocado](https://github.com/bigdatagenomics/avocado) operational and post preprint with publicized "best practice" workflow
- [ ] QC: Have [Quinine](https://github.com/bigdatagenomics/quinine) operational and post preprint

**Comment by heuermh** [comment]
Fixed by commit dd94f1d561ed95c28bfe7295f0bcfbf72b06f519
