### ISSUE TITLE
Address classes with lower than ideal coverage

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1405]
Now that we have easy-to-browse cover reports (#1404), let's do a deep dive and find out what code is not covered sufficiently. Would anyone be interested in helping? Perhaps we can split this effort up and divide-and-conquer?

**Comment by heuermh** [comment]
+1

**Comment by fnothaft** [comment]
Target is minimum 70% coverage per file.

- [ ] BQSR is uncovered, will be fixed as part of #1358
- [ ] Improve unit test coverage for NucleotideContigFragmentRDD, #1413
- [ ] Remove uncovered/unused Smith-Waterman code, #1413
- [ ] Write unittests for ParquetFileTraversable, #1415
- [ ] Add tests across the CLI, #1416
- [ ] Improved INDEL realignment coverage in #1412
- [ ] Improve JavaADAMContext coverage as #1387
- [ ] Delete low coverage `RichVariant` and `DecadentRead` classes as part of the #577 rich package refactor
- [ ] @heuermh sez he has a PR that cleans up some of the SaveArgs issues and which may improve coverage in the VCF save methods in GenotypeRDD -> #1327 
- [ ] Delete unused/uncovered Projection.apply methods as #1417
- [ ] Improve coverage of Feature encode/decode as #1418

**Comment by heuermh** [comment]
Closing as WontFix
